/**
 * Per-language humanization rules for the multilingual prompt builders in
 * lib/prompts.js and the language-aware Stage 1 analysis in
 * lib/stage1Processor.js.
 *
 * English is deliberately NOT in this map — it has its own hand-tuned prompts
 * and deterministic Stage 1 transforms. Each entry below documents the AI
 * tells of that specific language (they differ: German AI text leans on
 * Nominalstil, Spanish AI text on "no solo… sino también", French AI text on
 * "cela" and "permet de" chains). Do not add a language until the tells have
 * been researched — translated English rules are worse than no rules.
 *
 * Server-only: imported by the API pipeline, never shipped to the client.
 */

export const languageRules = {
  // ─── Spanish ────────────────────────────────────────────────────────────────
  es: {
    languageName: "Spanish",
    transitionTable: [
      ['"Sin embargo" / "No obstante"', '"Pero" / "Aun así"'],
      ['"Además" / "Asimismo" / "Adicionalmente"', '"Y" / "También" — or just continue the thought'],
      ['"Por lo tanto" / "Por consiguiente" / "En consecuencia"', '"Así que" / "Por eso"'],
      ['"Por otro lado" / "Por otra parte"', '"Ahora bien" / "Pero" — or delete'],
      ['"En primer lugar / En segundo lugar / Finalmente"', 'drop the scaffolding, just make the points'],
      ['"De esta manera" / "De este modo"', '"Así"'],
      ['"Con el fin de" / "Con el objetivo de"', '"Para"'],
      ['"A su vez"', '"También" — or delete'],
    ],
    deletePhrases: [
      "cabe destacar que", "cabe mencionar que", "cabe señalar que",
      "es importante destacar que", "es importante mencionar que",
      "es fundamental tener en cuenta que", "vale la pena mencionar que",
      "en conclusión", "en resumen", "en definitiva",
      "en el mundo actual", "en la era digital", "a lo largo de la historia",
      "sin lugar a dudas",
    ],
    aiWords: [
      "crucial", "fundamental", "esencial", "clave", "vital", "primordial",
      "sumergirse", "adentrarse", "fomentar", "potenciar", "transformador",
      "innovador", "revolucionario", "integral", "holístico", "robusto",
      "fluido", "panorama", "ámbito", "abanico", "gama",
      "desempeñar un papel crucial", "aprovechar al máximo",
    ],
    hedging: [
      "en cierta medida", "hasta cierto punto", "podría decirse que",
      "en muchos sentidos", "de alguna manera", "por lo general",
      "en términos generales", "generalmente hablando",
    ],
    plainWordSwaps: [
      ['"utilizar"', '"usar"'],
      ['"realizar" / "efectuar" / "llevar a cabo"', '"hacer"'],
      ['"obtener"', '"conseguir"'],
      ['"requerir" / "precisar"', '"necesitar"'],
      ['"demostrar"', '"mostrar"'],
      ['"numerosos"', '"muchos"'],
      ['"diversos"', '"varios"'],
      ['"aproximadamente"', '"unos"'],
      ['"individuos"', '"personas"'],
      ['"proporcionar" / "brindar"', '"dar"'],
      ['"poseer" / "contar con"', '"tener"'],
      ['"iniciar"', '"empezar"'],
      ['"finalizar"', '"terminar"'],
      ['"emplear"', '"usar"'],
    ],
    naturalTouches: [
      'Start 1–2 sentences per paragraph with "Y", "Pero" or "Así que".',
      'Join two short related clauses with just a comma, once: "No es complicado, solo lleva práctica."',
      'Drop in informal fillers, each at most once: "la verdad", "de hecho", "bastante", "un poco", "más bien", "eso sí".',
      'Ask one short rhetorical question where it fits naturally: "¿El resultado? Menos tiempo perdido."',
      'Use one slightly informal word where a formal one is expected: "un montón de" instead of "una gran cantidad de".',
      "Leave one sentence that is correct but not perfectly smooth, the way a fast typist would leave it.",
    ],
    extraNotes: [
      '"No solo… sino también" is one of the strongest AI tells in Spanish. Break the parallel structure: keep the more concrete half, drop or fold in the other.',
      'AI Spanish chains the verb "permitir" ("permite obtener…, lo que permite…"). Vary the verbs or restructure.',
      "The raya (—) used for asides is an AI tell in expository Spanish prose. Replace with commas or split the sentence. Keep inverted marks (¿ ¡) intact and correctly paired.",
      "Keep one consistent register (tú, usted or vos) matching the source text. Never switch mid-text.",
    ],
    stopWords: [
      "de", "la", "el", "en", "y", "a", "los", "las", "del", "al", "se", "que",
      "por", "un", "una", "unos", "unas", "con", "no", "su", "sus", "lo",
      "como", "más", "pero", "le", "les", "ya", "o", "u", "e", "este", "esta",
      "estos", "estas", "ese", "esa", "esos", "esas", "porque", "entre",
      "cuando", "muy", "sin", "sobre", "también", "me", "te", "nos", "hasta",
      "hay", "donde", "desde", "todo", "toda", "todos", "todas", "otro",
      "otra", "otros", "otras", "ni", "eso", "esto", "mucho", "poco", "algo",
      "nada", "cada", "ser", "es", "son", "era", "fue", "está", "están",
      "estar", "hacer", "tiene", "tienen", "puede", "pueden", "para",
    ],
  },

  // ─── French ─────────────────────────────────────────────────────────────────
  fr: {
    languageName: "French",
    transitionTable: [
      ['"Cependant" / "Toutefois" / "Néanmoins"', '"Mais" / "Cela dit"'],
      ['"De plus" / "En outre" / "Par ailleurs"', '"Et" / "Aussi" — or just continue the thought'],
      ['"Par conséquent" / "De ce fait" / "Ainsi"', '"Donc" / "Du coup" (if the register is informal)'],
      ['"En effet"', "delete it most of the time — just state the point"],
      ['"Dans un premier temps / Dans un second temps"', "drop the scaffolding, just make the points"],
      ['"Afin de" / "Dans le but de"', '"Pour"'],
      ['"En ce qui concerne" / "Concernant"', '"Pour" / "Sur"'],
      ['"C\'est pourquoi"', '"Voilà pourquoi" / "Du coup"'],
    ],
    deletePhrases: [
      "il est important de noter que", "il convient de souligner que",
      "il est essentiel de comprendre que", "force est de constater que",
      "il ne faut pas oublier que",
      "en conclusion", "en résumé", "en somme", "pour conclure",
      "dans un monde en constante évolution", "à l'ère du numérique",
      "sans aucun doute",
    ],
    aiWords: [
      "crucial", "essentiel", "primordial", "incontournable", "fondamental",
      "novateur", "révolutionnaire", "transformateur", "optimiser",
      "exploiter pleinement", "favoriser", "plonger dans", "paysage",
      "écosystème", "panoplie", "myriade", "éventail", "gamme",
      "jouer un rôle crucial", "holistique", "robuste", "fluide",
      "sans accroc", "renforcer",
    ],
    hedging: [
      "dans une certaine mesure", "en quelque sorte", "d'une certaine manière",
      "il se pourrait que", "on pourrait dire que", "de manière générale",
      "globalement", "en règle générale",
    ],
    plainWordSwaps: [
      ['"effectuer" / "réaliser"', '"faire"'],
      ['"s\'avérer"', '"être"'],
      ['"nécessiter" / "requérir"', '"demander" / "avoir besoin de"'],
      ['"démontrer"', '"montrer"'],
      ['"obtenir"', '"avoir"'],
      ['"posséder"', '"avoir"'],
      ['"de nombreux"', '"beaucoup de"'],
      ['"approximativement"', '"environ"'],
      ['"afin de"', '"pour"'],
      ['"suite à"', '"après"'],
      ['"au sein de"', '"dans"'],
      ['"débuter"', '"commencer"'],
      ['"achever"', '"finir"'],
    ],
    naturalTouches: [
      'Start 1–2 sentences per paragraph with "Et", "Mais" or "Donc".',
      'Replace one or two "cela" with "ça" — AI French writes "cela" everywhere; humans write "ça".',
      'Drop in informal fillers, each at most once: "en fait", "franchement", "plutôt", "un peu", "au fond", "d\'ailleurs", "bref".',
      'Join two short related clauses with just a comma, once: "Ce n\'est pas compliqué, ça demande juste de la pratique."',
      "Ask one short rhetorical question where it fits naturally.",
      "Leave one sentence that is correct but not perfectly smooth, the way a fast typist would leave it.",
    ],
    extraNotes: [
      '"Non seulement… mais aussi/également" is one of the strongest AI tells in French. Break the parallel structure: keep the more concrete half.',
      'AI French chains "permettre de" ("permet d\'obtenir…, ce qui permet de…"). Vary the verbs or restructure.',
      "The tiret cadratin (—) used for asides is an AI tell in expository French prose. Replace with commas or split the sentence. Keep French punctuation conventions (spaces before : ; ! ?, guillemets « ») intact.",
      "Keep the vous/tu register consistent with the source text. Never switch mid-text.",
    ],
    stopWords: [
      "le", "la", "les", "de", "des", "du", "un", "une", "et", "à", "au",
      "aux", "en", "dans", "sur", "sous", "pour", "par", "avec", "sans",
      "que", "qui", "dont", "où", "ne", "pas", "plus", "moins", "très",
      "bien", "mais", "ou", "donc", "ni", "car", "ce", "cet", "cette", "ces",
      "se", "sa", "son", "ses", "leur", "leurs", "nous", "vous", "ils",
      "elles", "il", "elle", "je", "tu", "on", "est", "sont", "être",
      "avoir", "ont", "était", "étaient", "fait", "faire", "comme", "tout",
      "tous", "toute", "toutes", "aussi", "autre", "autres", "même", "si",
      "y", "cela", "ça", "entre", "vers", "chez", "alors", "quand",
    ],
  },

  // ─── German ─────────────────────────────────────────────────────────────────
  de: {
    languageName: "German",
    transitionTable: [
      ['"Darüber hinaus" / "Des Weiteren" / "Zudem" / "Ferner"', '"Außerdem" / "Und" — or just continue the thought'],
      ['"Jedoch" (sentence-initial)', '"Aber"'],
      ['"Folglich" / "Demzufolge" / "Infolgedessen" / "Somit"', '"Deshalb" / "Also"'],
      ['"Nichtsdestotrotz"', '"Trotzdem"'],
      ['"Im Hinblick auf" / "In Bezug auf" / "Hinsichtlich"', '"Bei" / "Für" / "Was … angeht"'],
      ['"Zunächst / Anschließend / Abschließend" scaffolding', "drop it, just make the points"],
      ['"gewährleisten"', '"sicherstellen" / "sorgen für"'],
      ['"des Öfteren"', '"oft"'],
    ],
    deletePhrases: [
      "es ist wichtig zu beachten, dass", "es sei darauf hingewiesen, dass",
      "es ist erwähnenswert, dass", "man sollte bedenken, dass",
      "zusammenfassend lässt sich sagen", "abschließend lässt sich festhalten",
      "insgesamt zeigt sich",
      "in der heutigen digitalen welt", "in der heutigen zeit",
      "im laufe der jahre", "zweifellos", "ohne zweifel",
    ],
    aiWords: [
      "entscheidend", "essenziell", "unerlässlich", "maßgeblich", "zentral",
      "revolutionär", "innovativ", "bahnbrechend", "nahtlos", "ganzheitlich",
      "eintauchen", "fördern", "optimieren", "Landschaft (figurative)",
      "eine Vielzahl von", "eine breite Palette an", "ein breites Spektrum an",
      "spielt eine entscheidende Rolle", "von entscheidender Bedeutung",
      "robust", "dynamisch", "spannend (overused)", "wertvoll",
    ],
    hedging: [
      "in gewisser Weise", "bis zu einem gewissen Grad",
      "man könnte argumentieren", "tendenziell", "grundsätzlich",
      "im Allgemeinen", "in der Regel (overused)", "durchaus (overused)",
    ],
    plainWordSwaps: [
      ['"erhalten"', '"bekommen"'],
      ['"benötigen"', '"brauchen"'],
      ['"durchführen"', '"machen"'],
      ['"verfügen über"', '"haben"'],
      ['"sich befinden"', '"sein"'],
      ['"stellt … dar"', '"ist"'],
      ['"erfolgen"', "an active verb — say who does what"],
      ['"zahlreiche"', '"viele"'],
      ['"sämtliche"', '"alle"'],
      ['"circa"', '"etwa"'],
      ['"mittels"', '"mit"'],
      ['"seitens"', '"von"'],
      ['"in Anspruch nehmen"', '"nutzen"'],
      ['"zur Verfügung stellen"', '"geben"'],
    ],
    naturalTouches: [
      'Start 1–2 sentences per paragraph with "Und", "Aber" or "Also".',
      'Add one short verbless follow-up sentence: "Ganz einfach." / "Kein Wunder."',
      'Drop in informal fillers, each at most once: "eigentlich", "ehrlich gesagt", "ziemlich", "ein bisschen", "eben", "übrigens", "im Grunde".',
      "Ask one short rhetorical question where it fits naturally.",
      "Join two short related main clauses with just a comma, once — deliberately.",
      'Use one colloquial short form like "gibt\'s" or "geht\'s" — at most once, only if the tone allows it.',
    ],
    extraNotes: [
      'THE German AI tell is Nominalstil: "Die Implementierung der Lösung führt zu einer Verbesserung der Ergebnisse" → "Wenn man die Lösung einsetzt, werden die Ergebnisse besser." Break noun chains aggressively; put people or pronouns back as sentence subjects.',
      '"Nicht nur … sondern auch" and "sowohl … als auch" are strong AI tells — break the parallel structure.',
      "AI German overuses the Gedankenstrich (– / —) for asides. Use commas or split the sentence instead.",
      'Convert Passiv ("wird … durchgeführt") to Aktiv wherever possible — say who does what.',
      "Keep the Sie/du register consistent with the source text. Never switch mid-text.",
    ],
    stopWords: [
      "der", "die", "das", "den", "dem", "des", "ein", "eine", "einen",
      "einem", "einer", "eines", "und", "oder", "aber", "auch", "nicht",
      "mit", "für", "von", "zu", "im", "in", "am", "an", "auf", "aus",
      "bei", "nach", "über", "unter", "vor", "durch", "um", "ist", "sind",
      "war", "waren", "sein", "hat", "haben", "wird", "werden", "kann",
      "können", "muss", "müssen", "soll", "sollen", "wenn", "dann", "als",
      "wie", "so", "nur", "noch", "schon", "sehr", "mehr", "man", "sich",
      "es", "er", "sie", "wir", "ihr", "ich", "du", "dass", "was", "wer",
    ],
  },

  // ─── Portuguese ─────────────────────────────────────────────────────────────
  pt: {
    languageName: "Portuguese",
    transitionTable: [
      ['"No entanto" / "Entretanto" / "Contudo" / "Todavia"', '"Mas" / "Ainda assim"'],
      ['"Além disso" / "Ademais" / "Adicionalmente"', '"E" / "Também" — or just continue the thought'],
      ['"Portanto" / "Por conseguinte" / "Consequentemente"', '"Então" / "Por isso"'],
      ['"Por outro lado"', '"Agora" / "Mas" — or delete'],
      ['"Em primeiro lugar / Em segundo lugar / Por fim"', "drop the scaffolding, just make the points"],
      ['"Dessa forma" / "Desse modo" / "Assim sendo"', '"Assim"'],
      ['"A fim de" / "Com o objetivo de" / "Com o intuito de"', '"Para"'],
      ['"No que diz respeito a" / "Em relação a"', '"Sobre" / "Para"'],
    ],
    deletePhrases: [
      "vale ressaltar que", "vale destacar que", "cabe salientar que",
      "é importante ressaltar que", "é importante destacar que",
      "é fundamental compreender que", "não podemos esquecer que",
      "em suma", "em conclusão", "em resumo",
      "nos dias de hoje", "no mundo atual", "na era digital",
      "ao longo dos anos", "sem sombra de dúvida",
    ],
    aiWords: [
      "crucial", "fundamental", "essencial", "imprescindível", "primordial",
      "revolucionário", "inovador", "transformador", "otimizar",
      "potencializar", "alavancar", "fomentar", "mergulhar em", "panorama",
      "cenário (figurative)", "âmbito", "leque", "gama",
      "desempenha um papel crucial", "holístico", "robusto", "fluido",
      "impulsionar", "aprimorar (overused)",
    ],
    hedging: [
      "em certa medida", "até certo ponto", "pode-se argumentar que",
      "de certa forma", "de modo geral", "de maneira geral",
      "geralmente falando", "via de regra",
    ],
    plainWordSwaps: [
      ['"utilizar"', '"usar"'],
      ['"realizar" / "efetuar"', '"fazer"'],
      ['"obter"', '"conseguir"'],
      ['"necessitar"', '"precisar"'],
      ['"demonstrar"', '"mostrar"'],
      ['"inúmeros"', '"muitos"'],
      ['"diversos"', '"vários"'],
      ['"aproximadamente"', '"uns" / "cerca de"'],
      ['"indivíduos"', '"pessoas"'],
      ['"proporcionar" / "fornecer"', '"dar"'],
      ['"possuir" / "contar com"', '"ter"'],
      ['"auxiliar"', '"ajudar"'],
      ['"iniciar"', '"começar"'],
      ['"finalizar"', '"terminar"'],
    ],
    naturalTouches: [
      'Start 1–2 sentences per paragraph with "E", "Mas" or "Então".',
      'Join two short related clauses with just a comma, once: "Não é complicado, só exige prática."',
      'Drop in informal fillers, each at most once: "na verdade", "de fato", "bem", "meio" ("meio complicado"), "bastante", "aliás", "no fundo".',
      "Ask one short rhetorical question where it fits naturally.",
      'Use one slightly informal word where a formal one is expected: "um monte de" instead of "uma grande quantidade de".',
      "Leave one sentence that is correct but not perfectly smooth, the way a fast typist would leave it.",
    ],
    extraNotes: [
      '"Não apenas… mas também" is one of the strongest AI tells in Portuguese. Break the parallel structure: keep the more concrete half.',
      'AI Portuguese chains "permitir" ("permite obter…, o que permite…"). Vary the verbs or restructure.',
      "The travessão (—) used for asides is an AI tell in expository Portuguese prose. Replace with commas or split the sentence. (It stays normal for dialogue.)",
      "Keep the variant (Brazilian or European Portuguese) and the register (você/tu) consistent with the source text. Never mix variants.",
    ],
    stopWords: [
      "de", "a", "o", "que", "e", "do", "da", "em", "um", "para", "é",
      "com", "não", "uma", "os", "no", "se", "na", "por", "mais", "as",
      "dos", "das", "como", "mas", "foi", "ao", "ele", "ela", "tem", "à",
      "seu", "sua", "seus", "suas", "ou", "ser", "quando", "muito", "há",
      "nos", "já", "está", "estão", "eu", "também", "só", "pelo", "pela",
      "até", "isso", "entre", "era", "depois", "sem", "mesmo", "aos",
      "ter", "quem", "nas", "me", "esse", "essa", "eles", "elas", "você",
      "tinha", "foram", "num", "numa", "nem", "meu", "minha", "às", "qual",
    ],
  },
};

/** Languages the humanize pipeline accepts. English is the default. */
export const SUPPORTED_LANGUAGES = ["en", ...Object.keys(languageRules)];
